name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv .venv
        # Windows uses PowerShell, Ubuntu/macOS use bash
        if [ $RUNNER_OS != 'Windows' ]; then
          source .venv/bin/activate
        else
          .venv\Scripts\Activate.ps1
        fi
        pip install -e .
        pip install -r requirements.txt
      shell: bash

    - name: Run CLI basic check
      run: |
        if [ $RUNNER_OS != 'Windows' ]; then
          source .venv/bin/activate
        else
          .venv\Scripts\Activate.ps1
        fi
        python -m visualize_categorical.cli --n 10 --column test --out-dir ./figures
      shell: bash

    - name: Run tests
      run: |
        if [ $RUNNER_OS != 'Windows' ]; then
          source .venv/bin/activate
        else
          .venv\Scripts\Activate.ps1
        fi
        pytest -v
      shell: bash
