name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies on Ubuntu/macOS
      if: runner.os != 'Windows'
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -e .
        pip install -r requirements.txt
      shell: bash

    - name: Install dependencies on Windows
      if: runner.os == 'Windows'
      run: |
        python -m venv .venv
        .venv\Scripts\Activate.ps1
        pip install -e .
        pip install -r requirements.txt
      shell: pwsh

    - name: Run CLI basic check on Ubuntu/macOS
      if: runner.os != 'Windows'
      run: |
        source .venv/bin/activate
        python -m visualize_categorical.cli --n 10 --column test --out-dir ./figures
      shell: bash

    - name: Run CLI basic check on Windows
      if: runner.os == 'Windows'
      run: |
        .venv\Scripts\Activate.ps1
        python -m visualize_categorical.cli --n 10 --column test --out-dir ./figures
      shell: pwsh

    - name: Run tests on Ubuntu/macOS
      if: runner.os != 'Windows'
      run: |
        source .venv/bin/activate
        pytest -v
      shell: bash

    - name: Run tests on Windows
      if: runner.os == 'Windows'
      run: |
        .venv\Scripts\Activate.ps1
        pytest -v
      shell: pwsh
